### ISSUE TITLE
Installing with dotnet 4.0

### ISSUE THREAD

**Issue by razzeee** [kaa/nlog.targets.lumberjack#2]
Would it be possible to get a version, which is compatible to dotnet 4.0?

**Comment by kaa** [comment]
I guess so, there shouldn't really be anything 4.5 specific in the code, it just happened to be the version I was using. 

I'd just have to see how to structure the project to target different framework versions.

**Comment by razzeee** [comment]
that would be great, as I'm stuck on 4.0 for some time

**Comment by kaa** [comment]
Ouch, sorry. I'd completely forgotten it uses `async` and `await` which were introduced in 4.5. It seems it's a bit more work than just restructuring the .proj and .sln files.

I think it should be possible to retrofit it to be synchronous only on 4.0 and you could still make it asynchronous by wrapping it with an `AsyncTarget`. That seems like an interesting challenge - I'll see what I can come up with later.

**Comment by razzeee** [comment]
It might be possible with https://blogs.msdn.microsoft.com/bclteam/2013/04/17/microsoft-bcl-async-is-now-stable/ but I'm not sure if that's viable for a target library like this
